version: '3'

networks:
  laravel:
  cloudbox:
    external: true
  bridge:
    external: true

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx
    ports:
      - 8001:80
    volumes:
      - ${SRC}:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    environment:
      VIRTUAL_HOST: mosaic.jczr.dev
      VIRTUAL_PORT: 8001
      LETSENCRYPT_EMAIL: jcaezarrr@gmail.com
      LETSENCRYPT_HOST: mosaic.jczr.dev
    networks:
      - laravel
      - cloudbox

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: pos_v2
      MYSQL_USER: jczr
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - /opt/mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php
    volumes:
      - ${SRC}:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: composer
    volumes:
      - ${SRC}:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:latest
    container_name: npm
    volumes:
      - ${SRC}:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  bun:
    image: jarredsumner/bun:edge
    container_name: bun
    volumes:
      - ${SRC}:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['bun']
    networks:
      - laravel
      - cloudbox

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: artisan
    ports:
      - 6001:6001
    volumes:
      - ${SRC}:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
    environment:
      VIRTUAL_HOST: mosaic-ws.jczr.dev
      VIRTUAL_PORT: 6001
      LETSENCRYPT_HOST: mosaic-ws.jczr.dev
      LETSENCRYPT_EMAIL: jcaezarrr@gmail.com

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel
